### PR TITLE
perf: avoid allocations when filtering nodes

### PR DESCRIPTION
**Pull request by dignifiedquire**
After @whyrusleeping demonstrated us how to find slow code, I went and made this a bit faster.

Test used to profile is in `go-mfs`

screen shot 2018-08-28 at 21 43 50

pprof before
screen shot 2018-08-28 at 21 39 08

pprof after
screen shot 2018-08-28 at 21 37 57

### CODE REVIEW

**Comment by whyrusleeping** [comment]
nice improvement. 

Probably want to use the 'idiomatic' slice filter though: https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating

**Comment by dignifiedquire** [comment]
I found mixed reports about the actual speed of that. If doing the inplace version is what we want I‘ll compare the two and see from there.

cc @stebalien

**Comment by Stebalien** [comment]
In-place is definitely what we want. The slice trick may not be quite as fast but it's much easier to read and should be fast enough for us.

**Comment by dignifiedquire** [comment]
changed, speed improvements in that test are similar, so looks like go does optimize this nicely

**Pull request merged**
