### PR TITLE
staticcheck

### PR DESCRIPTION
**Pull request by coryschwartz**
This fixes small problems picked up by staticcheck.
The ones that remain are for the generated protobuf file, which I haven't regenerated.

For context: https://github.com/protocol/.github/issues/41

```
◉ staticcheck ./...
pb/merkledag.pb.go:213:10: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:217:11: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:222:10: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:226:11: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:231:10: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:309:10: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:313:11: error strings should not be capitalized (ST1005)
pb/merkledag.pb.go:317:10: error strings should not be capitalized (ST1005)
```

### CODE REVIEW

**Review by mvdan — APPROVED** [review]
I think we don't want to re-generate that protobuf code on purpose, to prevent changing CIDs.

**Comment by marten-seemann** [comment]
@mvdan This will fail on CI though. Any suggestion how to proceed here?

**Comment by mvdan** [comment]
Right. I think we have two options:

1) Manually fix the code to have no warnings, while being extra careful that we're not changing the behavior of the code in any way. The tests should cover most mistakes here, but I think we should also get 2+ thorough reviews.

2) Mark the entire file as "nolint" with staticcheck, assuming that's possible.

Option 2 is probably the easiest, assuming that none of the warnings point at real bugs.

**Comment by marten-seemann** [comment]
> 2. Mark the entire file as "nolint" with staticcheck, assuming that's possible.

According to https://staticcheck.io/docs, we could create a config file. Not sure if that allows us to exclude files though.

**Comment by mvdan** [comment]
There are comment directives to disable a check for the entire file: https://staticcheck.io/docs#file-based-linter-directives

**Comment by marten-seemann** [comment]
Apparently it's not possible to disable a rule for a specific file (but it might be possible to do it for an entire directory, which would work here): https://github.com/dominikh/go-tools/issues/429.
I have to admit I failed to figure out how to write such a rule in TOML though.

**Comment by mvdan** [comment]
What about that `//lint:file-ignore` I linked to in my last comment?

**Comment by marten-seemann** [comment]
`-: Near line 0 (last key parsed ''): bare keys cannot contain '/' (compile)`

Doesn't seem to be valid TOML.

**Comment by mvdan** [comment]
That goes in the Go source file, not a TOML config.

**Comment by marten-seemann** [comment]
That might work, but I'd like to avoid editing generated files. We have a lot of protobuf files across our code base.

**Comment by mvdan** [comment]
I would hope that this kind of thing is only necessary for go-merkledag's ancient gogo-protobuf generated code though. Most other repos should be using a recent protoc-gen-go version, which I hope does not generate any vet or staticcheck warnings.

**Comment by Stebalien** [comment]
> That might work, but I'd like to avoid editing generated files. We have a lot of protobuf files across our code base.

We've already intentionally edited this file to ensure that we'll fail a test if we try to regenerate it. Essentially, I _don't_ consider it to be an "autogenerated" file at this point. I'll file a new PR to remove that comment....

**Comment by rvagg** [comment]
https://github.com/ipfs/go-merkledag/pull/71

**Pull request merged**
