### PR TITLE
Fix bug in dagutils MergeDiffs.

### PR DESCRIPTION
**Pull request by nasdf**
This fixes a bug where conflicts were also returned as changes when merged.

### CODE REVIEW

**Comment by rvagg** [comment]
I think this is OK, but would you mind trying to add a simple test case for it?

**Comment by nasdf** [comment]
Yeah I'll update when I have some free time this week.

**Comment by nasdf** [comment]
@rvagg  I cleaned up the diff function and added some tests for it as well.  Hopefully this all looks good and can be merged soon.

**Comment by nasdf** [comment]
@rvagg Can you take a look at my changes?

**Comment by nasdf** [comment]
@Stebalien Can you take a look at this?

**Comment by aschmahmann** [comment]
@nasdf a lot of people are unavailable over the next little bit due to holidays (Dec - Jan is frequently rough for getting things merged in). Things should start picking back up later this month and then we can hopefully get this taken care of.

**Review by rvagg — APPROVED** [review]
This is a very nice code cleanup in general, and tests, and I think it's just the single `delete` that might be doing all of the fix work here, so thanks for going the extra mile! lgtm.

**Pull request merged**
