### PR TITLE
Display missing blocks in error message

### PR DESCRIPTION
**Pull request by hinshun**
Error message when missing blocks in a DAG needs more information.

Before change:
```
ipfs --offline get QmRtNyeCQ198AjEy7SfGsfzd6m43r4AfBXyxxG2LDgmSJv
Saving file(s) to QmRtNyeCQ198AjEy7SfGsfzd6m43r4AfBXyxxG2LDgmSJv
 41.74 MiB / 41.74 MiB [===========] 100.00% 0s
Error: failed to fetch all nodes
Error: failed to fetch all nodes
```

After change:
```
ipfs --offline get QmRtNyeCQ198AjEy7SfGsfzd6m43r4AfBXyxxG2LDgmSJv
Saving file(s) to QmRtNyeCQ198AjEy7SfGsfzd6m43r4AfBXyxxG2LDgmSJv
 41.74 MiB / 41.74 MiB [===========] 100.00% 0s
Error: failed to fetch nodes: [QmSWvkGknu8feDQTQPcV2AA9WxDVw8cN4wbPtuCMxiC1SY QmRv9Z9cYZGGx6oa4aEUNpGQx7rGsjcgn1aUTRJvL6eMby]
Error: failed to fetch nodes: [QmSWvkGknu8feDQTQPcV2AA9WxDVw8cN4wbPtuCMxiC1SY QmRv9Z9cYZGGx6oa4aEUNpGQx7rGsjcgn1aUTRJvL6eMby]
```

### CODE REVIEW

**Comment by hinshun** [comment]
Curious why you think it has a significant performance implication?

The differences from what I see are:
- `if count != len(keys) {` vs `if set.Len() != 0 {`
  - `set.Len` is implemented by checking the length of a map.
- `count++` vs `set.Remove(nd.Cid())`
  - `set.Remove` is implemented by deleting a key from a map.

**Comment by Stebalien** [comment]
I'm worried about the error formatting. We could be missing hundreds of CIDs. Really, it probably won't be much of a performance issue (unless we end up storing these errors somewhere) but it'll definitely generate really long error messages.

**Comment by hinshun** [comment]
Okay that makes sense. In my case I still would like to know exactly which CIDs are missing in order to debug my application using IPFS, I'm perf testing various P2P scenarios, and one part of that is to shard a IPLD DAG across a IPFS cluster (i.e. node A gets ~1/3 of graph by size in bytes, node B gets another ~1/3, node C gets ~1/3). There was some bugs I had to work out in the sharding code and this made it difficult to diagnose what was going on.

Maybe we can clarify the error message `failed to fetch all nodes` by clarifying it failed to fetch `x` nodes to at least disambiguate it from network/etc errors. Is it possible to debug log it so the CIDs are still available?

I also wrote a small benchmark in case its interesting:
```sh
# master
❯ go test -run BenchmarkGetMany -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/ipfs/go-merkledag
BenchmarkGetMany1-8     	  100000	     10904 ns/op	     984 B/op	      20 allocs/op
BenchmarkGetMany10-8    	  100000	     11213 ns/op	     984 B/op	      20 allocs/op
BenchmarkGetMany100-8   	  100000	     10583 ns/op	     984 B/op	      20 allocs/op
PASS
ok  	github.com/ipfs/go-merkledag	6.397s

# hinshun:missing-nodes
❯ go test -run BenchmarkGetMany -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/ipfs/go-merkledag
BenchmarkGetMany1-8     	  100000	     11157 ns/op	    1176 B/op	      22 allocs/op
BenchmarkGetMany10-8    	  100000	     13112 ns/op	    1176 B/op	      22 allocs/op
BenchmarkGetMany100-8   	  100000	     12980 ns/op	    1176 B/op	      22 allocs/op
PASS
ok  	github.com/ipfs/go-merkledag	5.561s
```

```golang
func benchmarkGetMany(i int, b *testing.B) {
	ctx := context.Background()

	var nodes []ipld.Node
	for j := 0; j < i; j++ {
		nd := NodeWithData([]byte{byte(j)})
		nodes = append(nodes, nd)
	}

	var cids []cid.Cid
	for _, nd := range nodes {
		cids = append(cids, nd.Cid())
	}

	dagservs := make([]ipld.DAGService, b.N)
	for n := 0; n < b.N; n++ {
		srv := NewDAGService(dstest.Bserv())

		if err := srv.AddMany(ctx, nodes); err != nil {
			panic(err)
		}

		dagservs[n] = srv
	}

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		nds := dagservs[n].GetMany(ctx, cids)
		for _ = range nds {
		}
	}
}

func BenchmarkGetMany1(b *testing.B) { benchmarkGetMany(1, b) }

func BenchmarkGetMany10(b *testing.B) { benchmarkGetMany(1, b) }

func BenchmarkGetMany100(b *testing.B) { benchmarkGetMany(1, b) }
```

**Comment by Stebalien** [comment]
> benchmark

My performance concern was more about when we're missing blocks (drop the `AddMany` calls). In that case, the slow down looks like:

```
benchmark                 old ns/op     new ns/op     delta
BenchmarkGetMany1-4       7053          13330         +89.00%
BenchmarkGetMany10-4      8691          13055         +50.21%
BenchmarkGetMany100-4     8403          13370         +59.11%
```

However, this is, admittedly, a micro-benchmark. Really, let's just forget I said anything. This isn't an issue. The only real issues are:

1. The length of the error (ux).
2. The fact that the error won't actually include _all_ missing blocks.

> Okay that makes sense. In my case I still would like to know exactly which CIDs are missing

So, I suggested returning one CID because this won't return _all_ CIDs regardless. That is, `ipfs get` will traverse the graph, calling `GetMany` on the children of each node it finds. However, it'll stop when the first `GetMany` fails. That means it won't report missing nodes from other parts of the graph, just the children that are missing from the first block missing children.

> Maybe we can clarify the error message failed to fetch all nodes by clarifying it failed to fetch x nodes to at least disambiguate it from network/etc errors. Is it possible to debug log it so the CIDs are still available?

Yeah, that shouldn't be an issue (although, personally, I'd just insert print statements as required).

**Comment by hinshun** [comment]
Thanks for clarifying, I missed the fact that its only from the first block that failed to get all its children. I think ideally, the error message would look something like: `failed to fetch %d children of %s`, or if we want to incorporate one child: `failed to fetch all children of %s: %s (%d missing children)` where the one child is the first lexicographical sorted missing child?

**Comment by Stebalien** [comment]
> ideally, the error message would look something like:

Unfortunately, GetMany doesn't know that, it just knows that it's supposed to fetch a set of nodes. The part that's fetching children of blocks is in go-unixfs.

**Pull request closed without merging**
