### PR TITLE
fix: slightly reduce memory usage when walking large directory trees

### PR DESCRIPTION
**Pull request by Stebalien**
This adds up quick.

### CODE REVIEW

**Comment by lanzafame** [comment]
@Stebalien I know we don't currently have much benchmarking infra in place but I would love to see small 'obvious' perf improvements like this have a benchmark added or at the least the output of a benchmark before/after. I know in this case that it is an obvious win but not every case is that way and we don't have a practice of confirming our perf improvements on the 'function' level.

**Comment by Stebalien** [comment]
For cases like this, I confirm by re-running the daemon on a known workload and checking. This is one of the reasons I want to get pprof profiles from benchmarks. Given a predictable workload, we can easily detect memory usage regressions by looking at the top ten allocators.

**Comment by lanzafame** [comment]
> I confirm by re-running the daemon on a known workload and checking

That only helps you contribute perf improvements though 😄

**Comment by Stebalien** [comment]
Ideally, we'd have something continuously running common workloads and taking profiles. But that's mostly useful for catching regressions. When _making_ improvements, profiling is really the only way to go.

**Pull request merged**
